### ISSUE TITLE
Extend definition of `name` property of a `dictInfo` object (to discuss)

### ISSUE THREAD

**Issue by bblodfon** [vsm/vsm-dictionary#12]
The PubDictionaries API returns information on the dictionaries such as:
http://pubdictionaries.org/dictionaries/PTO-all.json
http://pubdictionaries.org/dictionaries/UBERON-AE.json

Should we map the given `description` to the `name` attribute of the `dictInfo` object (thus extending the definition a little bit)? Consider vsm-box's handling of `dictInfo.name` and size? Or maybe we could consider an extra `z` object property for `dictInfo` as well or too much/keep it simple?

**Comment by stcruy** [comment]
The purpose of both dictInfo `name` and `abbrev` is to orient the user about what dictionary a term comes from. They are used like that in vsm-box's terms' popup: as just a short text.

Those two examples seem to not have a name (in the vsm-dictionary sense) at all, but only an (actually) abbreviation; and the description seems to be a full name in example 1, but it becomes an actual (multisentence) description on example 2. So the description should not be relied upon as a 'name'.

So I'd suggest to map PubDictionaries' `name` to dictInfo's `name`, and leave dictInfo's `abbrev` empty.
(And I do not recommend this:  Or else, assign name to di.abbrev, and leave di.name empty – but since PubDicts calls it "name", we should not expect that it will be a short abbreviation in general).
